### ISSUE TITLE
Additional DLL Needed

### ISSUE THREAD

**Issue by xul8tr** [lkosson/reportviewercore#1]
Hello,

Is it possible you can also convert the WebForms control?

This is the package I'm currently using: Microsoft.ReportingServices.ReportViewerControl.WebForms.150.1404.0

**Comment by lkosson** [comment]
Hi.

Converting WebForms ReportViewer control to .NET Core would require rewrite of ~80% of the code, because the control is tightly coupled to ASP.NET architecture, which is significantly different from ASP.NET Core.

If you are porting WebForms or MVC application to .NET Core, as a stopgap I'd suggest rendering report to a PDF on a server-side (you can use DLLs from this repo to do it) and sending it as-is to browser. There are no free interactive web-based ReportViewer implementations I'm aware of; you could use paid ones, though.

**Comment by xul8tr** [comment]
Will this .NET Core implementation work inside say an azure function?

**Comment by lkosson** [comment]
No idea, really. I'm still working on a version with removed .NET Framework and WinForms dependencies, which should make it much more suitable for SaaS/cloud deployment. Until then feel free to try running WinForms version, as long as you don't try opening any windows, it should work.

**Comment by xul8tr** [comment]
So, I've written a whole dynamic universal C# Reporting API in ASP.NET because... well... I didn't have a choice. We have the SSRS reporting project where the reports are created and then on build it copies the compiled RDL's to the API project as RDLC. The API is just one endpoint that accepts the report name and the parameters for the report. My code reads the RDLC XML and extracts all of the report parameters and data source info. It then set's the report object params with the parameters sent to the API. For each data source, I query SQL to extract the stored proc parameters (if the data source isn't an inline SQL query) and then execute the stored proc after mapping the provided parameter's values to the parameters the stored proc needs. I then add the data table result to the report object's data sources.

LocalReports bug (maybe): 
The following method for setting the reporting URL will trigger the SubReportProcessing event (at least on the version I was using originally about 8mo ago).


```
var reportViewer new ReportViewer();
var localReport = reportViewer.LocalReport;
var reportPath = @"c:\path\to\report.rdlc";

localReport.LoadReportDefinition(new StreamReader(reportPath)); //Doesn't trigger the SubreportProcessing event
localReport.ReportPath = reportPath; //Does trigger the SubreportProcessing event

localReport.SubreportProcessing += ReportRDLC_SubReportProcessing;
```

When I tried this a few months ago I couldn't get it to work very with as an azure function, at least not big complicated reports.  Long story short, I built a universal reporting engine around rdl/rdlc but Azure WebApps will close the connection between the customer-facing API and the azure WebApplication running the Reporting API if the rendering over something like 240 seconds. And since LocalReport.Render doesn't have like an async byte stream I can return I just have to wait for the Render method to finish.

If you could update and have the RenderMethod essentially accept a ref param that was List<byte[]> and after every page was rendered it added the page's bytes to the list that sure would solve this problem.

Alternatively, if I can get it working in an Azure Function, with our consumption plan they don't have timeouts.

**Comment by xul8tr** [comment]
When I get to SetParameters with my rdlc files (which is actually just a direct copy of the rdl from my reporting project bin dir)

   at Microsoft.Reporting.ReportCompiler.CompileReport(ICatalogItemContext context, Byte[] reportDefinition, Boolean generateExpressionHostWithRefusedPermissions, ControlSnapshot& snapshot) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.Reporting\ReportCompiler.cs:line 28
   at Microsoft.Reporting.LocalService.GetCompiledReport(PreviewItemContext itemContext, Boolean rebuild, ControlSnapshot& snapshot) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.Reporting\LocalService.cs:line 695
   at Microsoft.Reporting.LocalService.CompileReport() in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.Reporting\LocalService.cs:line 757
   at Microsoft.Reporting.LocalService.Microsoft.Reporting.ILocalProcessingHost.CompileReport() in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.Reporting\LocalService.cs:line 751
   at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession() in C:\repo\reportviewercore\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\LocalReport.cs:line 802

**Comment by lkosson** [comment]
If your report takes a few minutes to render, consider running it in separate, background thread or as an independent job and poll for completion. I don't think moving to async stream would change much, since you wouldn't get even one byte until whole report completes.

As for report compilation errors - ReportViewer uses RDLC, not RDL definitions. If you're 100% certain this report works in original ReportViewer, I'd say your report uses some VB expressions that Roslyn compiler somehow doesn't understand. Try looking in inner compilation exception from Roslyn, if there is any.

**Comment by xul8tr** [comment]
The report I was testing with does in deed have VB in it. 


   at Microsoft.ReportingServices.RdlExpressions.VBExpressionCodeProvider.CompileAssemblyFromDom(CompilerParameters options, CodeCompileUnit[] compilationUnits) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.RdlExpressions\VBExpressionCodeProvider.cs:line 39
   at Microsoft.ReportingServices.RdlExpressions.ExprHostCompiler.InternalCompile(AppDomain compilationTempAppDomain, Boolean refusePermissions) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.RdlExpressions\ExprHostCompiler.cs:line 276
   at Microsoft.ReportingServices.RdlExpressions.ExprHostCompiler.<>c__DisplayClass46_0.<Compile>b__0() in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.RdlExpressions\ExprHostCompiler.cs:line 180
   at Microsoft.ReportingServices.Diagnostics.RevertImpersonationContext.Run(ContextBody callback) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.Diagnostics\RevertImpersonationContext.cs:line 15
   at Microsoft.ReportingServices.RdlExpressions.ExprHostCompiler.Compile(IExpressionHostAssemblyHolder expressionHostAssemblyHolder, AppDomain compilationTempAppDomain, Boolean refusePermissions, PublishingVersioning versioning) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.RdlExpressions\ExprHostCompiler.cs:line 178
   at Microsoft.ReportingServices.ReportPublishing.ReportPublishing.Phase3(ParameterInfoCollection& parameters, Dictionary`2& groupingExprCountAtScope) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.ReportPublishing\ReportPublishing.cs:line 17557
   at Microsoft.ReportingServices.ReportPublishing.ReportPublishing.InternalCreateIntermediateFormat(Stream definitionStream, String& description, String& language, ParameterInfoCollection& parameters, DataSourceInfoCollection& dataSources, DataSetInfoCollection& sharedDataSetReferences, UserLocationFlags& userReferenceLocation, ArrayList& dataSetsName, Boolean& hasExternalImages, Boolean& hasHyperlinks, Byte[]& dataSetsHash) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.ReportPublishing\ReportPublishing.cs:line 201
   at Microsoft.ReportingServices.ReportPublishing.ReportPublishing.CreateIntermediateFormat(Byte[] definition, String& description, String& language, ParameterInfoCollection& parameters, DataSourceInfoCollection& dataSources, DataSetInfoCollection& sharedDataSetReferences, UserLocationFlags& userReferenceLocation, ArrayList& dataSetsName, Boolean& hasExternalImages, Boolean& hasHyperlinks, Byte[]& dataSetsHash) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.ReportPublishing\ReportPublishing.cs:line 180
   at Microsoft.ReportingServices.ReportProcessing.ReportProcessing.CompileOdpReport(PublishingContext reportPublishingContext, PublishingErrorContext errorContext, String& reportDescription, String& reportLanguage, ParameterInfoCollection& parameters, DataSourceInfoCollection& dataSources, DataSetInfoCollection& sharedDataSetReferences, UserLocationFlags& userReferenceLocation, ArrayList& dataSetsName, Boolean& hasExternalImages, Boolean& hasHyperlinks, Byte[]& dataSetsHash) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.ReportProcessing\ReportProcessing.cs:line 25040
   at Microsoft.ReportingServices.ReportProcessing.ReportProcessing.CreateIntermediateFormat(PublishingContext reportPublishingContext) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.ReportProcessing\ReportProcessing.cs:line 25002

------------------------------
ExprHostCompiler.cs on line 276

add the line to watch this is the error 

   at Microsoft.ReportingServices.RdlExpressions.VBExpressionCodeProvider.CompileAssemblyFromDom(CompilerParameters options, CodeCompileUnit[] compilationUnits) in C:\repo\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.RdlExpressions\VBExpressionCo
deProvider.cs:line 39

and that line is:
var assemblyFile = Path.GetTempFileName();
