### ISSUE TITLE
FileNotFoundException: System.ServiceModel.Primitives, Version=4.8.1.0

### ISSUE THREAD

**Issue by RichardD2** [lkosson/reportviewercore#108]
Trying to use this library in .NET 6, I get a `FileNotFoundException` as soon as I call `SetParameters`:
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.8.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Source=Microsoft.ReportViewer.NETCore
  StackTrace:
   at Microsoft.Reporting.NETCore.SoapReportExecutionService.SetExecutionId(String executionId)
   at Microsoft.Reporting.NETCore.ServerReport.get_Service()
   at Microsoft.Reporting.NETCore.ServerReport.EnsureExecutionSession()
   at Microsoft.Reporting.NETCore.ServerReport.SetParameters(IEnumerable`1 parameters)
```

The code is simply:

```csharp
ServerReport report = new()
{
    ReportServerUrl = new("http://localhost/ReportServer_SQLEXPRESS"),
    ReportPath = "/Invoice",
};

ReportParameter[] parameters =
{
    new ReportParameter("InvoiceId", "1")
};

report.SetParameters(parameters);
```

Using v15.1.17:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.17" />
    </ItemGroup>
</Project>
```

**Comment by RichardD2** [comment]
After adding references to the missing `System.ServiceModel.Http` package, that error is resolved; I now get a different error.
