### ISSUE TITLE
Having Issue when exporting xlsx file multiple time

### ISSUE THREAD

**Issue by HamzaDati123** [lkosson/reportviewercore#109]
Stack Trace:

   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings)
   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at Microsoft.Reporting.NETCore.LocalReport.Render(String format, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at Microsoft.Reporting.NETCore.Report.Render(String format, String deviceInfo, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at Microsoft.Reporting.NETCore.Report.Render(String format, String deviceInfo)
   at Microsoft.Reporting.NETCore.Report.Render(String format)
   at E_Compensate_V3.Web.Controllers.ReportController.<PrepareReport>d__27.MoveNext() in\Controllers\ReportController.cs:line 816
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at E_Compensate_V3.Web.Controllers.ReportController.<GetPayRollReport>d__26.MoveNext() in \Controllers\ReportController.cs:line 659

**Comment by lkosson** [comment]
And what's the actual/nested exception?

**Comment by HamzaDati123** [comment]
This is the Error Message: An error occurred during local report processing.
This is the source of the error: Microsoft.ReportViewer.NETCore
This is the Inner Exception: System.ArgumentException: Parameter is not valid.     at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)     at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)     at System.Drawing.Image.Save(Stream stream, ImageFormat format)     at Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.GetInvalidImage(IExcelGenerator excel, Dictionary`2 sharedImageCache, Boolean& isShared)     at Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.RenderImage(IExcelGenerator excel, Dictionary`2 sharedImageCache, RPLElementProps itemProps, Int32 topRow, Int32 bottomRow, Int32 leftColumn, Int32 rightColumn, IRowItemStruct item)     at Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.RenderItem(IExcelGenerator excel, Dictionary`2 sharedImageCache, RPLElementProps props, Byte type, Int32 topRow, Int32 bottomRow, Int32 leftColumn, Int32 rightColumn, Boolean verticallyMerged, Boolean& autosizableGrow, Boolean& autosizableShrink, BorderInfo borderDef, IRowItemStruct item)     at Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.RenderNewItem(IRowItemStruct item, Int32 top, Int32 topRow, IExcelGenerator excel, String pageContentKey, Dictionary`2 sharedBorderCache, Dictionary`2 sharedImageCache, Boolean& autosizableGrow, Boolean& autosizableShrink)     at Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.RenderPageToExcel(IExcelGenerator excel, String key, Dictionary`2 sharedBorderCache, Dictionary`2 sharedImageCache)     at Microsoft.ReportingServices.Rendering.ExcelRenderer.MainEngine.RenderRPLPage(RPLReport report, Boolean headerInBody, Boolean suppressOutlines)     at Microsoft.ReportingServices.Rendering.ExcelRenderer.ExcelRenderer.Render(Report report, NameValueCollection reportServerParameters, NameValueCollection deviceInfo, NameValueCollection clientCapabilities, Hashtable& renderProperties, CreateAndRegisterStream createAndRegisterStream)

**Comment by HamzaDati123** [comment]
I am getting this error when exporting for PDF and Excel as well.

**Comment by lkosson** [comment]
`LayoutEngine.GetInvalidImage` method is strictly related to XLSX renderer. Do you get this error on non-windows platform? If so, try installing `libgdiplus` and/or adding `System.Drawing.EnableUnixSupport` runtime swith as described in https://aka.ms/systemdrawingnonwindows if you use .NET 6+.
