### ISSUE TITLE
Problem authenticating with NTLM

### ISSUE THREAD

**Issue by mfirthOmx** [lkosson/reportviewercore#156]
I am having a problem connecting to the reporting server

It connects fine in development and works.

How ever when I publish the code base to a server: I get NTLM unauthorized errors when attempting to attach to the report server.

Is there anything anyone may know of that can alleviate this problem?

ERROR 2023-10-14 18:51:47,354 [14   ] Mvc.ExceptionHandling.AbpExceptionFilter - The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'NTLM'.
System.ServiceModel.Security.MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'NTLM'.
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.LoadReport3(LoadReport3Request)
   at Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.ReportExecutionServiceSoapClient.Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.ReportExecutionServiceSoap.LoadReport3(LoadReport3Request request)
   at Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.ReportExecutionServiceSoapClient.LoadReport3(TrustedUserHeader TrustedUserHeader, String Report, String HistoryID, ServerInfoHeader& ServerInfoHeader, ExecutionInfo3& executionInfo)
   at Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.ReportExecutionServiceSoapClient.LoadReport3(String Report, String HistoryID)
   at Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.RSExecutionConnection.<>c__DisplayClass34_0.<LoadReport>b__0()
   at Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.RSExecutionConnection.ProxyMethodInvocation.Execute[TReturn](RSExecutionConnection connection, ProxyMethod`1 sql16Method, ProxyMethod`1 katmaiMethod, ProxyMethod`1 yukonMethod)
   at Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.RSExecutionConnection.LoadReport(String Report, String HistoryID)
   at Microsoft.Reporting.NETCore.SoapReportExecutionService.LoadReport(String report, String historyId)
   at Microsoft.Reporting.NETCore.ServerReport.EnsureExecutionSession()
   at Microsoft.Reporting.NETCore.ServerReport.GetParameters()
   at Reporting.ReportFactory.GetParameters() in /Users/matthewfirth/Documents/OmniDev/OmniView2API_NET_7/Reporting/ReportFactory.cs:line 108
   at BizTech.OmniViewPortal.Bo.Reporting.ReportingAppService.GetFormProxy(Int32 reportId, Nullable`1 machineId, Nullable`1 startDate, Nullable`1 endDate) in /Users/matthewfirth/Documents/OmniDev/OmniView2API_NET_7/src/BizTech.OmniViewPortal.Application/Bo/Reporting/ReportingAppService.cs:line 52
   at lambda_method1300(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by mfirthOmx** [comment]
Just to add a note: I was able to access the server by changing the subnet. If I accessed at localhost or any other subnet the calls work. If I try to access from the same subnet: the calls all get NTLM failures.

**Comment by lkosson** [comment]
See #120

**Comment by mfirthOmx** [comment]
That’s due to the with method on ssrs being Kerberos rather than NTLM, th ssrs server is configured with NTLM and works if you come in from a different destination subnet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
