### ISSUE TITLE
Won't render WORD format.

### ISSUE THREAD

**Issue by hovek** [lkosson/reportviewercore#16]
For any report that has an image:

Could not find the resource "Microsoft.ReportingServices.Rendering.WordRenderer.Images.resources" among the resources "Microsoft.ReportingServices.Diagnostics.Utilities.ErrorStrings.resources", "Microsoft.ReportingServices.OnDemandReportRendering.RenderErrors.resources", "Microsoft.ReportingServices.RdlObjectModel.SR.resources", "Microsoft.ReportingServices.RdlObjectModel.SRErrors.resources", "Microsoft.ReportingServices.Rendering.ExcelRenderer.ExcelRenderRes.resources", "Microsoft.ReportViewer.Common.Microsoft.ReportingServices.Rendering.ExcelRenderer.Images.resources", "Microsoft.ReportingServices.Rendering.HPBProcessing.HPBRes.resources", "Microsoft.ReportViewer.Common.Microsoft.ReportingServices.Rendering.HPBProcessing.Images.resources", "Microsoft.ReportingServices.Rendering.ImageRenderer.ImageRendererRes.resources", "Microsoft.ReportViewer.Common.Microsoft.ReportingServices.Rendering.ImageRenderer.Images.resources", ... embedded in the assembly "Microsoft.ReportViewer.Common", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.

   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name)
   at Microsoft.ReportingServices.Rendering.WordRenderer.PictureDescriptor..cctor()

**Comment by lkosson** [comment]
Fixed.

**Comment by hovek** [comment]
> Fixed.

Thanks.
When will the new NuGet be available?

**Comment by lkosson** [comment]
Should be now available.
