### ISSUE TITLE
PDF generation fails on Linux Docker container

### ISSUE THREAD

**Issue by kganesan0108** [lkosson/reportviewercore#21]
I have implemented this on my local windows machine and it works fine, but when I go and deploy this on a linux docker container it thows an error as shown below 
```

System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. 
In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory   
at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)   
at System.Drawing.SafeNativeMethods.Gdip..cctor()   --- End of inner exception stack trace ---   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, IntPtr scan0, IntPtr& bitmap)   
at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height)   
at Microsoft.ReportingServices.Rendering.ImageRenderer.GraphicsBase..ctor(Single dpiX, Single dpiY)   
at Microsoft.ReportingServices.Rendering.ImageRenderer.PDFWriter.BeginReport(Int32 dpiX, Int32 dpiY)   
at Microsoft.ReportingServices.Rendering.ImageRenderer.PDFRenderer.Render(Report report, NameValueCollection deviceInfo, Hashtable renderProperties, CreateAndRegisterStream createAndRegisterStream)   
at Microsoft.ReportingServices.Rendering.ImageRenderer.RendererBase.Render(Report report, NameValueCollection reportServerParameters, NameValueCollection deviceInfo, NameValueCollection clientCapabilities, Hashtable& renderProperties, CreateAndRegisterStream createAndRegisterStream)
```

We tried to fix it by modifying the docker file using the solution provided here [Here](https://stackoverflow.com/a/59252639/562424)

but now it gives an error below

```
System.DllNotFoundException: Unable to load shared library 'usp10.dll' or one of its dependencies. 
In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libusp10.dll: 
cannot open shared object file: No such file or directory   
at Microsoft.ReportingServices.Rendering.RichText.Win32.ScriptItemize(String pwcInChars, Int32 cInChars, Int32 cMaxItems, SCRIPT_CONTROL& psControl, SCRIPT_STATE& psState, SCRIPT_ITEM[] pItems, Int32& pcItems)   
at Microsoft.ReportingServices.Rendering.RichText.Paragraph.ScriptItemize(Directions direction)   
at Microsoft.ReportingServices.Rendering.RichText.TextBox.ScriptItemize()   
at Microsoft.ReportingServices.Rendering.HPBProcessing.TextBox.GetRichTextBox()   
at Microsoft.ReportingServices.Rendering.HPBProcessing.TextBox.CalculateVerticalSize(PageContext pageContext)   
at Microsoft.ReportingServices.Rendering.HPBProcessing.TextBox.DetermineVerticalSize(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors)   
at Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem.CalculateVertical(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, PageItem[] siblings, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors, Nullable`1 sourceWidth)   
at Microsoft.ReportingServices.Rendering.HPBProcessing.PageItemContainer.DetermineContentVerticalSize(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors, Boolean resolveState, Boolean resolveItem)   
at Microsoft.ReportingServices.Rendering.HPBProcessing.PageItemContainer.DetermineVerticalSize(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors)   
at Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem.CalculateVertical(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, PageItem[] siblings, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors, Nullable`1 sourceWidth)   
at Microsoft.ReportingServices.Rendering.HPBProcessing.ReportSection.NextPage(RPLWriter rplWriter, Int32 pageNumber, Int32 totalPages, Double top, Double availableHeight, ReportSection nextSection, Boolean isFirstSectionOnPage)   at Microsoft.ReportingServices.Rendering.HPBProcessing.Report.NextPage(RPLWriter rplWriter, Int32 totalPages)   
at Microsoft.ReportingServices.Rendering.HPBProcessing.HPBProcessing.GetNextPage(RPLReport& rplReport)   
at Microsoft.ReportingServices.Rendering.ImageRenderer.PDFRenderer.Render(Report report, NameValueCollection deviceInfo, Hashtable renderProperties, CreateAndRegisterStream createAndRegisterStream)   
at Microsoft.ReportingServices.Rendering.ImageRenderer.RendererBase.Render(Report report, NameValueCollection reportServerParameters, NameValueCollection deviceInfo, NameValueCollection clientCapabilities, Hashtable& renderProperties, CreateAndRegisterStream createAndRegisterStream)
```

is there any workaround to this?

**Comment by lkosson** [comment]
PDF exporter depends heavily on font measurement functions provided by Windows Uniscribe DLLs and won't work on Linux or Mac OS. As of now, there is no workaround to get PDF output on Linux. Your best bet is to switch to HTML, DOCX or XLSX output.

**Comment by ShivaKumarCT** [comment]
I'm facing the same issue, is there any workaround to this issue?

System.DllNotFoundException: Unable to load shared library 'usp10.dll' or one of its dependencies. 
In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libusp10.dll: 
cannot open shared object file: No such file or directory

**Comment by lkosson** [comment]
Not much changed since last comment. Rewriting PDF renderer using cross-platform tools requires a full-time commitment and would take hundreds of hours, if not more.

**Comment by davimorao** [comment]
> PDF exporter depends heavily on font measurement functions provided by Windows Uniscribe DLLs and won't work on Linux or Mac OS. As of now, there is no workaround to get PDF output on Linux. Your best bet is to switch to HTML, DOCX or XLSX output.



I'm trying to switch to HTML format but it generates the below error:

----------------------------------------------------------------
Microsoft.Reporting.NETCore.LocalProcessingException:
   at Microsoft.Reporting.NETCore.LocalReport.InternalRender (Microsoft.ReportViewer.NETCore, Version=15.1.17.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.Reporting.NETCore.LocalReport.InternalRender (Microsoft.ReportViewer.NETCore, Version=15.1.17.0, Culture=neutral, PublicKeyToken=null)
----------------------------------------------------------------

Performing tests I noticed that if the report has a graph the error occurs, using only tables and simple elements it works normally
Do you have an example with the linux image or dockerfile that supports the ?

**Comment by lkosson** [comment]
What's the actual (inner) exception? Can you provide a stack trace?

**Comment by davimorao** [comment]
> What's the actual (inner) exception? Can you provide a stack trace?

Inner exception System.ArgumentNullException handled at Microsoft.Reporting.NETCore.LocalReport.InternalRender:
   at System.ThrowHelper.ThrowArgumentNullException (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Collections.Generic.Dictionary`2.TryInsert (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Collections.Generic.Dictionary`2.Add (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Reporting.StreamCache.StreamCallback (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.Reporting.NETCore.CreateAndRegisterStreamTypeConverter+<>c__DisplayClass1_0.<ToOuterType>b__0 (Microsoft.ReportViewer.NETCore, Version=15.1.17.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.CreateStream (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.ServerDynamicImageRenderer.RenderDynamicImage (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.ServerDynamicImageRenderer.RenderReportItem (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.RenderReportItem (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.RenderCellItem (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.GenerateTableLayoutContent (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.GenerateHTMLTable (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.RectangleRenderer.RenderRectangle (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.RenderHtmlBody (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.Html5ServerRenderer.Render (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.Html5RenderingExtension.InternalRender (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.ReportingServices.Rendering.HtmlRenderer.RenderingExtensionBase.Render (Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null)

**Comment by lkosson** [comment]
There is a problem with rendering a chart, a map or a gauge in your report; it doesn't produce PNG image to embed in HTML. I can't reproduce the error locally, so either modify a `Report.rdlc` from the sample project `ReportViewerCore.Sample.Console` in this repo to cause the same behavior or remove any maps or charts in your report one by one and see which one causes problems.

**Comment by lkosson** [comment]
If you are using .NET 6, see #105 - `System.Drawing` used by charts and maps got deprecated and requires a runtime switch to enable. Chart renderer swallows all exceptions, so to see if this is the cause, look for first-chance exceptions thrown before the one you have submitted above.

**Comment by davimorao** [comment]
> There is a problem with rendering a chart, a map or a gauge in your report; it doesn't produce PNG image to embed in HTML. I can't reproduce the error locally, so either modify a `Report.rdlc` from the sample project `ReportViewerCore.Sample.Console` in this repo to cause the same behavior or remove any maps or charts in your report one by one and see which one causes problems.


I changed the `ReportViewerCore.Sample.Console` project to catch the error, follow the steps:

1 - In the Archive [Program.cs](https://github.com/lkosson/reportviewercore/blob/d8d8f50627445233cd0a4d841c0f9cbd3a11a4b0/ReportViewerCore.Sample.Console/Program.cs#L13)

I changed these lines:
var pdf = report.Render("HTML5");
File.WriteAllBytes("report.pdf", pdf);

For:
var reportRendered = report.Render("HTML5");
File.WriteAllBytes("report.html", reportRendered);

2 - Include a graph in Report.rdlc
![image](https://user-images.githubusercontent.com/12645048/192806909-e6ceec13-0abf-4c54-8da4-f1cc5ff3a75f.png)

**With these steps in windows environments it works correctly, generating an html file as follows:**
![image](https://user-images.githubusercontent.com/12645048/192807211-98604853-e1f6-417a-ba7c-fbc63c75e908.png)

**==============================================================**

**Now to reproduce the error in question, I added the dockerfile below:**

`FROM mcr.microsoft.com/dotnet/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["ReportViewerCore.Sample.Console/ReportViewerCore.Sample.Console.csproj", "ReportViewerCore.Sample.Console/"]
COPY ["Microsoft.ReportViewer.NETCore/Microsoft.ReportViewer.NETCore.csproj", "Microsoft.ReportViewer.NETCore/"]
COPY ["Microsoft.ReportViewer.Common/Microsoft.ReportViewer.Common.csproj", "Microsoft.ReportViewer.Common/"]
COPY ["Microsoft.ReportViewer.DataVisualization/Microsoft.ReportViewer.DataVisualization.csproj", "Microsoft.ReportViewer.DataVisualization/"]
COPY ["Microsoft.ReportViewer.ProcessingObjectModel/Microsoft.ReportViewer.ProcessingObjectModel.csproj", "Microsoft.ReportViewer.ProcessingObjectModel/"]
RUN dotnet restore "ReportViewerCore.Sample.Console/ReportViewerCore.Sample.Console.csproj"
COPY . .
WORKDIR "/src/ReportViewerCore.Sample.Console"
RUN dotnet build "ReportViewerCore.Sample.Console.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ReportViewerCore.Sample.Console.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ReportViewerCore.Sample.Console.dll"]`


Running in a linux container as per docker file, I got the following error:

> Microsoft.Reporting.NETCore.LocalProcessingException
  HResult=0x80131500
  Message=An error occurred during local report processing.
  Source=Microsoft.ReportViewer.NETCore
  StackTrace:
   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings) in C:\Users\Davi\Documents\Davi\Git\reportviewercore-master\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\LocalReport.cs:line 1029
   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings) in C:\Users\Davi\Documents\Davi\Git\reportviewercore-master\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\LocalReport.cs:line 986
   at Microsoft.Reporting.NETCore.LocalReport.Render(String format, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings) in C:\Users\Davi\Documents\Davi\Git\reportviewercore-master\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\LocalReport.cs:line 977
   at Microsoft.Reporting.NETCore.Report.Render(String format, String deviceInfo, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings) in C:\Users\Davi\Documents\Davi\Git\reportviewercore-master\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\Report.cs:line 152
   at Microsoft.Reporting.NETCore.Report.Render(String format, String deviceInfo) in C:\Users\Davi\Documents\Davi\Git\reportviewercore-master\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\Report.cs:line 147
   at Microsoft.Reporting.NETCore.Report.Render(String format) in C:\Users\Davi\Documents\Davi\Git\reportviewercore-master\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\Report.cs:line 137
   at ReportViewerCore.Console.Program.Main(String[] args) in C:\Users\Davi\Documents\Davi\Git\reportviewercore-master\ReportViewerCore.Sample.Console\Program.cs:line 13

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.Reporting.StreamCache.StreamCallback(string, string, System.Text.Encoding, string, bool, Microsoft.ReportingServices.Interfaces.StreamOper) in StreamCache.cs
    Microsoft.Reporting.NETCore.CreateAndRegisterStreamTypeConverter.ToOuterType.AnonymousMethod__0(string, string, System.Text.Encoding, string, bool, Microsoft.ReportingServices.Interfaces.StreamOper) in CreateAndRegisterStreamTypeConverter.cs
    Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.CreateStream(string, string, System.Text.Encoding, string, bool, Microsoft.ReportingServices.Interfaces.StreamOper) in HTML5Renderer.cs
    Microsoft.ReportingServices.Rendering.HtmlRenderer.ServerDynamicImageRenderer.RenderDynamicImage(Microsoft.ReportingServices.Rendering.RPLProcessing.RPLItemMeasurement, Microsoft.ReportingServices.Rendering.RPLProcessing.RPLDynamicImageProps) in ServerDynamicImageRenderer.cs
    Microsoft.ReportingServices.Rendering.HtmlRenderer.ServerDynamicImageRenderer.RenderReportItem(Microsoft.ReportingServices.Rendering.RPLProcessing.RPLElement, Microsoft.ReportingServices.Rendering.RPLProcessing.RPLItemMeasurement, Microsoft.ReportingServices.Rendering.HtmlRenderer.StyleContext, ref int, bool, bool) in ServerDynamicImageRenderer.cs
    Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.RenderReportItem(Microsoft.ReportingServices.Rendering.RPLProcessing.RPLElement, Microsoft.ReportingServices.Rendering.RPLProcessing.RPLElementProps, Microsoft.ReportingServices.Rendering.RPLProcessing.RPLElementPropsDef, Microsoft.ReportingServices.Rendering.RPLProcessing.RPLItemMeasurement, Microsoft.ReportingServices.Rendering.HtmlRenderer.StyleContext, int, bool, bool) in HTML5Renderer.cs
    Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.RenderCellItem(Microsoft.ReportingServices.Rendering.HtmlRenderer.PageTableCell, int, bool, bool) in HTML5Renderer.cs
    Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.GenerateTableLayoutContent(Microsoft.ReportingServices.Rendering.HtmlRenderer.PageTableLayout, Microsoft.ReportingServices.Rendering.RPLProcessing.RPLItemMeasurement[], bool, bool, bool, int, bool, Microsoft.ReportingServices.Rendering.HtmlRenderer.SharedListLayoutState, System.Collections.Generic.List<Microsoft.ReportingServices.Rendering.RPLProcessing.RPLTablixMemberCell>, Microsoft.ReportingServices.Rendering.RPLProcessing.IRPLStyle, bool) in HTML5Renderer.cs
    Microsoft.ReportingServices.Rendering.HtmlRenderer.HTML5Renderer.GenerateHTMLTable(Microsoft.ReportingServices.Rendering.RPLProcessing.RPLItemMeasurement[], float, float, float, float, int, bool, Microsoft.ReportingServices.Rendering.HtmlRenderer.SharedListLayoutState, System.Collections.Generic.List<Microsoft.ReportingServices.Rendering.RPLProcessing.RPLTablixMemberCell>, Microsoft.ReportingServices.Rendering.RPLProcessing.IRPLStyle, bool) in HTML5Renderer.cs
    ...
    [Call Stack Truncated]

Inner Exception 1:
ArgumentNullException: Value cannot be null. (Parameter 'key')


**Important point, when removing the graphic above the html file is generated correctly in the linux container**

**Comment by lkosson** [comment]
Thanks, I have reproduced the error in my environment. The root cause is missing `libgdiplus` package in base image, as in the first comment in this thread. To confirm that's the case, add following line at the start of the sample project:

`AppDomain.CurrentDomain.FirstChanceException += (sender, e) => System.Console.WriteLine(e.Exception.ToString());`

and see if you get `System.DllNotFoundException` inside `System.TypeInitializationException` complaining about `libgdiplus` or `liblibgdiplus`. If so, add following to your Dockerfile:

`RUN apt-get update && apt-get install -y libgdiplus`

If the problem still persists, try starting the program using:

`LD_DEBUG=libs dotnet ReportViewerCore.Sample.Console.dll`

It should output lots of file probing messages. Examine ones above the first first-chance exception referencing `libgdiplus`. It should contain something like 

`find library=libgdiplus.so.so [0]; searching`

followed by a list of locations checked for the library. See if any of those locations contains the requested file.

**Comment by davimorao** [comment]
> Thanks, I have reproduced the error in my environment. The root cause is missing `libgdiplus` package in base image, as in the first comment in this thread. To confirm that's the case, add following line at the start of the sample project:
> 
> `AppDomain.CurrentDomain.FirstChanceException += (sender, e) => System.Console.WriteLine(e.Exception.ToString());`
> 
> and see if you get `System.DllNotFoundException` inside `System.TypeInitializationException` complaining about `libgdiplus` or `liblibgdiplus`. If so, add following to your Dockerfile:
> 
> `RUN apt-get update && apt-get install -y libgdiplus`
> 
> If the problem still persists, try starting the program using:
> 
> `LD_DEBUG=libs dotnet ReportViewerCore.Sample.Console.dll`
> 
> It should output lots of file probing messages. Examine ones above the first first-chance exception referencing `libgdiplus`. It should contain something like
> 
> `find library=libgdiplus.so.so [0]; searching`
> 
> followed by a list of locations checked for the library. See if any of those locations contains the requested file.

I made the adjustments and it worked correctly in a linux container, thanks!

**Comment by pciliberto** [comment]
Hello, I have the same problem, after libgdiplus was not found I installed them via dockerfile but now show always the following erro when I render in PDF format: 
"System.DllNotFoundException: Unable to load shared library 'usp10.dll' or one of its dependencies". 
the prblem is showed when the the repor is rendered in the PDF format. If i put HTML5 it works, but a report in html is not good and don't follow the margin layout set in the rdlc, indeed, the html report become very large and if i try to do a second  convertuion using external libraries frome html file to pdf the layout is not good at all because the html report has a layout that don't follow the rdlc. I believe this is a critical issue because if the project cannot be used in the linux container then it cannot be used the whole project. Thanks for the attention

**Comment by lkosson** [comment]
PDF renderer is not supported in Linux and there is no easy way to add such support.

**Comment by lkosson** [comment]
There is now a workaround available for PDF support on non-Windows platforms. While not ideal, it should cover your use case. See [Linux rendering workaround](https://github.com/lkosson/reportviewercore#linux-rendering-workaround) on main page for details.

**Comment by GripService** [comment]
> There is now a workaround available for PDF support on non-Windows platforms. While not ideal, it should cover your use case. See [Linux rendering workaround](https://github.com/lkosson/reportviewercore#linux-rendering-workaround) on main page for details.

its not in detail and do not know how to install wine from docker container 'Linux' and help ?

**Comment by lkosson** [comment]
Try asking on docker or wine support groups. If you have an issue related directly to this (Report Viewer Core) project, please open a new issue here.

**Comment by kevinta8x** [comment]
So, does anyone solved this issue.
I'm stuck here

**Comment by jakapwat** [comment]
same issue
