### ISSUE TITLE
Render PDF is not working as expected. 

### ISSUE THREAD

**Issue by BriMacD2000** [lkosson/reportviewercore#25]
Hi, 

Great work.  I have an issue with the PDF rendering not working when running in Azure as an App Service.  It works fine in Visual Studio on my desktop, but not in the App Service. 

Any help with this would be greatly appreciated

Regards

Brian

**Comment by lkosson** [comment]
What error do you get when rendering PDF using Azure ASE? Does HTML/DOCX/XLS rendering work correctly there?

**Comment by lkosson** [comment]
What's the stack trace of inner exception (ArgumentException)?

**Comment by BriMacD2000** [comment]
Inner Exception Stack Trace:

  at System.Drawing.Graphics.GetHdc()
   at Microsoft.ReportingServices.Rendering.RichText.LineBreaker.Flow(TextBox textBox, Graphics g, FontCache fontCache, FlowContext flowContext, Boolean keepLines, Single& height)
   at Microsoft.ReportingServices.Rendering.RichText.TextBox.MeasureFullHeight(TextBox textBox, Graphics g, FontCache fontCache, FlowContext flowContext, Single& contentHeight)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.PageContext.PageContextCommon.MeasureFullTextBoxHeight(TextBox textBox, FlowContext flowContext, Single& contentHeight)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.TextBox.CalculateVerticalSize(PageContext pageContext)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.TextBox.DetermineVerticalSize(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem.CalculateVertical(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, PageItem[] siblings, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors, Nullable`1 sourceWidth)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.PageItemContainer.DetermineContentVerticalSize(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors, Boolean resolveState, Boolean resolveItem)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.PageItemContainer.DetermineVerticalSize(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem.CalculateVertical(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, PageItem[] siblings, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors, Nullable`1 sourceWidth)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.ReportSection.NextPage(RPLWriter rplWriter, Int32 pageNumber, Int32 totalPages, Double top, Double availableHeight, ReportSection nextSection, Boolean isFirstSectionOnPage)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.Report.NextPage(RPLWriter rplWriter, Int32 totalPages)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.HPBProcessing.GetNextPage(RPLReport& rplReport)
   at Microsoft.ReportingServices.Rendering.ImageRenderer.PDFRenderer.Render(Report report, NameValueCollection deviceInfo, Hashtable renderProperties, CreateAndRegisterStream createAndRegisterStream)
   at Microsoft.ReportingServices.Rendering.ImageRenderer.RendererBase.Render(Report report, NameValueCollection reportServerParameters, NameValueCollection deviceInfo, NameValueCollection clientCapabilities, Hashtable& renderProperties, CreateAndRegisterStream createAndRegisterStream)

Source: System.Drawing.Common

Message: Parameter is not valid

Data Collection is empty.

Regards

Brian

**Comment by lkosson** [comment]
There seems to be a limitation in Azure ASE preventing usage of GDI subsystem on some plans; see: https://social.msdn.microsoft.com/Forums/Lync/en-US/1a530e8e-0738-4f85-982f-ad81254635c0/

There is not much I can do - Reporting Services heavily uses GDI/User for all its rendereres. Perhaps consider using a dedicated VM to host your service.

**Comment by BriMacD2000** [comment]
Ok.  Thanks I was just really checking that it was not a weird bug.  It is just Azure being a bit of an issue.  Thanks again for all your help.

**Comment by BriMacD2000** [comment]
Just for reference it works on a B1 plan or higher in App Services.  Thanks again for all your help.
