### ISSUE TITLE
Issue on Ubuntu

### ISSUE THREAD

**Issue by verloka** [lkosson/reportviewercore#27]
I have an exception while generating local rdl reports

```
.ctor exception: Culture is not supported. (Parameter 'culture')
4096 (0x1000) is an invalid culture identifier., Stack trace:    at System.Globalization.CultureInfo..ctor(Int32 culture, Boolean useUserOverride)
   at Microsoft.ReportingServices.ReportIntermediateFormat.RecordSetInfo..ctor(Boolean readerExtensionsSupported, Boolean persistCalculatedFields, DataSetInstance dataSetInstance, DateTime reportExecutionTime)
   at Microsoft.ReportingServices.OnDemandProcessing.ProcessingDataReader..ctor(OnDemandProcessingContext odpContext, DataSetInstance dataSetInstance, String dataSetName, IDataReader sourceReader, Boolean hasServerAggregateMetadata, String[] aliases, String[] names, DataSourceErrorInspector errorInspector)
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeDataSet.CreateProcessingDataReader(IDataReader reader, DataSourceErrorInspector errorInspector, Boolean readerExtensionsSupportedLocal)
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeDataSet.StoreDataReader(IDataReader reader, DataSourceErrorInspector errorInspector)
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeLiveQueryExecutor.RunLiveQuery(List`1 queryParams, Object[] paramValues)
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeDataSet.RunEmbeddedQuery(List`1 queryParams, Object[] paramValues)
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeDataSet.RunDataSetQuery()
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeDataSet.InitializeAndRunLiveQuery()
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeAtomicDataSet.InitializeRowSourceAndProcessRows(ExecutedQuery existingQuery)
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeAtomicDataSet.Process(ExecutedQuery existingQuery)
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeAtomicDataSet.ProcessConcurrent(Object threadSet)
```

Please help or provide me an advice. Thanks!

**Comment by lkosson** [comment]
It looks like ReportViewer (both original and core version) doesn't play nice with custom cultures and .NET Core on Ubuntu defaults to one. Try setting `System.Threading.Thread.CurrentThread.CurrentCulture` for a thread used to render your RDLC to some predefined culture like `new CultureInfo("en-GB")` or even `CultureInfo.InvariantCulture`.

**Comment by verloka** [comment]
> It looks like ReportViewer (both original and core version) doesn't play nice with custom cultures and .NET Core on Ubuntu defaults to one. Try setting `System.Threading.Thread.CurrentThread.CurrentCulture` for a thread used to render your RDLC to some predefined culture like `new CultureInfo("en-GB")` or even `CultureInfo.InvariantCulture`.

I found the problem. It works on Windows, but does not work on Linux unless the language is configured in the report (blank field).

![image](https://user-images.githubusercontent.com/5623092/111141705-864c6000-858c-11eb-8bd8-4b9aedb9ec72.png)
