### ISSUE TITLE
PDF & Image generation fails on Windows Nano Server Docker container

### ISSUE THREAD

**Issue by josellm** [lkosson/reportviewercore#42]
Hi,

We need to containerize a legacy application using rdlc report and migrate to .net 5.0. We uses your porting succesfully but testing with a NanoServer returns this error when render reports to PDF/TIFF:

`Microsoft.Reporting.NETCore.LocalProcessingException: An error occurred during local report processing.
 ---> System.NotImplementedException: The method or operation is not implemented.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.ReportingServices.Rendering.RichText.Paragraph.ScriptItemize(Directions direction)
   at Microsoft.ReportingServices.Rendering.RichText.TextBox.ScriptItemize()
   at Microsoft.ReportingServices.Rendering.HPBProcessing.TextBox.GetRichTextBox()
   at Microsoft.ReportingServices.Rendering.HPBProcessing.TextBox.CalculateVerticalSize(PageContext pageContext)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.TextBox.DetermineVerticalSize(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem.CalculateVertical(PageContext pageContext, Double topInParentSystem, Double bottomInParentSystem, PageItem[] siblings, List`1 ancestors, Boolean& anyAncestorHasKT, Boolean hasUnpinnedAncestors, Nullable`1 sourceWidth)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.Tablix.RowInfo.CalculateVerticalLastDetailCell(PageContext context, Boolean firstTouch, Boolean delayCalc)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.Tablix.CreateDetailCell(Tablix tablix, TablixMember colMemberParent, Int32 colGridIndex, RowInfo rowInfo, PageContext pageContext)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.Tablix.TraverseColumnMembers(Tablix tablix, TablixMember colMemberParent, Int32 parentColIndex, RowInfo currRowInfo, Boolean create, Double startInTablix, Double endInTablix, Int32& detailCellIndex, Int32& visibleSpan, List`1 detailCellsState, PageContext pageContext)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.Tablix.TraverseColumnMembers(Tablix tablix, TablixMember colMemberParent, Int32 parentColIndex, RowInfo currRowInfo, Boolean create, Double startInTablix, Double endInTablix, Int32& detailCellIndex, Int32& visibleSpan, List`1 detailCellsState, PageContext pageContext)
   at Microsoft.ReportingServices.Rendering.HPBProcessing.Tablix.CreateDetailRow(Tablix tablix, TablixMember rowMemberParent, Int32 parentRowIndex, Int32 parentColIndex, PageContext pageContext)`

The problem is that NanoServer is a headless SO and no support GDI+ and Uniscribe libraries. There is planned that ReportViewerCore works on Linux or NanoServer in this case?

Thanks

**Comment by lkosson** [comment]
Hello.

You might try putting Uniscribe DLLs from full Windows Server in your application directory in the container and see if it helps. As for now there are no workarounds to get PDF working on Linux or on Windows without GUI support installed. Eventually I might rewrite whole renderer to use other cross-platform typography library, but I cannot provide any timeline due to large amount of work required for such change.

Your best bet now is to switch to rendering to DOCX or HTML.
