### ISSUE TITLE
Invalid report error while rendor in .NET Core application, but this rdlc file works in windows application

### ISSUE THREAD

**Issue by pandithuraik** [lkosson/reportviewercore#6]
I am getting error as below for rdlc report when I use this library, error while redner. but this report working in other windows 
based application. Please help as soon aspossible.

**CODE :** 
       byte[] reportresult = null;
            try
            {
                //using (FileStream stream = new FileStream(reportpath, FileMode.Open))
                //{
                //reportDefinition = stream;

                LocalReport report = new LocalReport();

                report.DataSources.Clear();
                
                report.ReportPath = reportpath;
                    //report.LoadReportDefinition(reportDefinition);

                    AddDataSources(reportparameters, report);
                    //report.Refresh();
                    ****reportresult = report.Render("PDF");****

                //}
            }

**ERROR :**

Error : Source : **Microsoft.ReportViewer.NETCore Inner Exception : System.ApplicationException: The report definition for report SalesPrint has not been specified**
 ---> System.IO.FileNotFoundException: Could not find file D:\Production\QuickAPI\QuickAPI\Reports\SalesPrint.rdlc.
File name: D:\Production\QuickAPI\QuickAPI\Reports\SalesPrint.rdlc
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Microsoft.ReportingServices.StandalonePreviewStore.GetReportDefinition(PreviewItemContext itemContext)
   --- End of inner exception stack trace ---
   at Microsoft.ReportingServices.StandalonePreviewStore.GetReportDefinition(PreviewItemContext itemContext)
   at Microsoft.Reporting.LocalService.GetCompiledReport(PreviewItemContext itemContext, Boolean rebuild, ControlSnapshot& snapshot)
   at Microsoft.Reporting.LocalService.CompileReport()
   at Microsoft.Reporting.LocalService.Microsoft.Reporting.ILocalProcessingHost.CompileReport()
   at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession() Stack:    at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession()
   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings)
   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at Microsoft.Reporting.NETCore.LocalReport.Render(String format, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at Microsoft.Reporting.NETCore.Report.Render(String format, String deviceInfo, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at Microsoft.Reporting.NETCore.Report.Render(String format, String deviceInfo)
   at Microsoft.Reporting.NETCore.Report.Render(String format)
   at QuickAPI.Helpers.HelperReport.Report(ReportParameters reportparameters) in D:\QuickSales\QuickAPI\QuickAPI\QuickAPI\Helpers\HelperReport.cs:line 41

**Comment by lkosson** [comment]
Are you sure RDLC file actually exists at that path? Try opening FileStream directly, as in commented code you've submitted.
