### ISSUE TITLE
Missing Switch implementation in field expressions

### ISSUE THREAD

**Issue by AmroOsama** [lkosson/reportviewercore#67]
Hello, 
Thanks a lot for this great project.

I just found out that 'switch'  is not supported/implemented.
I just replaced the switch statement with nested IIF statements, so IIF is working fine.

Just wanted to point this out incase anyone faces the same problem.

Have a nice day!

`LocalProcessingException > An error occurred during local report processing.
at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession()
   at Microsoft.Reporting.NETCore.LocalReport.SetParameters(IEnumerable`1 parameters)

Inner > DefinitionInvalidException > The definition of the report '' is invalid.
	   at Microsoft.Reporting.ReportCompiler.CompileReport(ICatalogItemContext context, Byte[] reportDefinition, Boolean generateExpressionHostWithRefusedPermissions, ControlSnapshot& snapshot)
	   at Microsoft.Reporting.LocalService.GetCompiledReport(PreviewItemContext itemContext, Boolean rebuild, ControlSnapshot& snapshot)
	   at Microsoft.Reporting.LocalService.CompileReport()
	   at Microsoft.Reporting.LocalService.Microsoft.Reporting.ILocalProcessingHost.CompileReport()
	   at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession()

Inner > ReportProcessingException > An unexpected error occurred
in Report Processing.
	   at Microsoft.ReportingServices.ReportProcessing.ReportProcessing.CreateIntermediateFormat(PublishingContext reportPublishingContext)
	   at Microsoft.Reporting.ReportCompiler.CompileReport(ICatalogItemContext context, Byte[] reportDefinition, Boolean generateExpressionHostWithRefusedPermissions, ControlSnapshot& snapshot)

Inner > InvalidOperationException > Expr3end(0) : error BC30451: 'Switch' is not declared. It may be inaccessible due to its protection level.
	   at Microsoft.ReportingServices.RdlExpressions.VBExpressionCodeProvider.CompileAssemblyFromDom(CompilerParameters options, CodeCompileUnit[] compilationUnits)
	   at Microsoft.ReportingServices.RdlExpressions.ExprHostCompiler.InternalCompile(AppDomain compilationTempAppDomain, Boolean refusePermissions)
	   at Microsoft.ReportingServices.RdlExpressions.ExprHostCompiler.<>c__DisplayClass46_0.<Compile>b__0()
	   at Microsoft.ReportingServices.Diagnostics.RevertImpersonationContext.Run(ContextBody callback)
	   at Microsoft.ReportingServices.RdlExpressions.ExprHostCompiler.Compile(IExpressionHostAssemblyHolder expressionHostAssemblyHolder, AppDomain compilationTempAppDomain, Boolean refusePermissions, PublishingVersioning versioning)
	   at Microsoft.ReportingServices.ReportPublishing.ReportPublishing.Phase3(ParameterInfoCollection& parameters, Dictionary`2& groupingExprCountAtScope)
	   at Microsoft.ReportingServices.ReportPublishing.ReportPublishing.InternalCreateIntermediateFormat(Stream definitionStream, String& description, String& language, ParameterInfoCollection& parameters, DataSourceInfoCollection& dataSources, DataSetInfoCollection& sharedDataSetReferences, UserLocationFlags& userReferenceLocation, ArrayList& dataSetsName, Boolean& hasExternalImages, Boolean& hasHyperlinks, Byte[]& dataSetsHash)
	   at Microsoft.ReportingServices.ReportPublishing.ReportPublishing.CreateIntermediateFormat(Byte[] definition, String& description, String& language, ParameterInfoCollection& parameters, DataSourceInfoCollection& dataSources, DataSetInfoCollection& sharedDataSetReferences, UserLocationFlags& userReferenceLocation, ArrayList& dataSetsName, Boolean& hasExternalImages, Boolean& hasHyperlinks, Byte[]& dataSetsHash)
	   at Microsoft.ReportingServices.ReportProcessing.ReportProcessing.CompileOdpReport(PublishingContext reportPublishingContext, PublishingErrorContext errorContext, String& reportDescription, String& reportLanguage, ParameterInfoCollection& parameters, DataSourceInfoCollection& dataSources, DataSetInfoCollection& sharedDataSetReferences, UserLocationFlags& userReferenceLocation, ArrayList& dataSetsName, Boolean& hasExternalImages, Boolean& hasHyperlinks, Byte[]& dataSetsHash)
	   at Microsoft.ReportingServices.ReportProcessing.ReportProcessing.CreateIntermediateFormat(PublishingContext reportPublishingContext)
`

**Comment by lkosson** [comment]
It looks like .NET function providing support for `Switch` expression in VB ([link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction.switch?view=net-5.0)) is implemented in .NET 5 and newer, but not in .NET Core 3.1.

You can either replace it with `Iif`s ([supported since .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction.iif?view=netcore-3.1)) or upgrade your application to .NET 5.

**Comment by mreinagithub** [comment]
> It looks like .NET function providing support for `Switch` expression in VB ([link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction.switch?view=net-5.0)) is implemented in .NET 5 and newer, but not in .NET Core 3.1.
> 
> You can either replace it with `Iif`s ([supported since .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction.iif?view=netcore-3.1)) or upgrade your application to .NET 5.

Hi lkosson!, migrating to .NET6.0 in my case solves Switch expression's issue. 
However, i'm using Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package, for .net6.0 and it needs the package Microsoft.CodeAnalysis.Common 4.0.1 or superior, and with this package i'm getting the following error when trying to render a report:

"TypeLoadException: Method 'FilterDiagnostic' in type 'Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilationOptions' from assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation."

Can you upgrade dependence to a newer version of CodeAnalysis?. see it possible?

Thanks!!!

**Comment by lkosson** [comment]
Hi,

upgrading `Microsoft.CodeAnalysis.Common` version causes conflicts with `Microsoft.VisualStudio.Web.CodeGeneration.Design` package installed by VS when adding a new scaffolded project item. I think the only way to fully support .NET 5+ is to finally add a multi-framework targeting in this project and provide separate binaries for different .NET versions.

**Comment by mreinagithub** [comment]
I see, that's would be a good solution.

**Comment by lkosson** [comment]
I have published new packages (15.1.16) which provide separate references to `Microsoft.CodeAnalysis.*` depending on selected .NET version.
