### ISSUE TITLE
Culture is not supported issue in .NET 6.0

### ISSUE THREAD

**Issue by wahab2512** [lkosson/reportviewercore#75]
Microsoft.Reporting.NETCore.LocalProcessingException: 'An error occurred during local report processing.'

Exception 1: ProcessingAbortedException: An error has occurred during report processing.
Exception 2: CultureNotFoundException: Culture is not supported. Arg_ParamName_Name
Argument_CultureInvalidIdentifier

InnerException: Culture is not supported. (Parameter 'culture')
4096 (0x1000) is an invalid culture identifier.

StackTrace:    at Microsoft.ReportingServices.OnDemandProcessing.AbortHelper.ThrowIfAborted(CancelationTrigger cancelationTrigger, String uniqueName)
   at Microsoft.ReportingServices.OnDemandProcessing.RetrievalManager.FetchData()
   at Microsoft.ReportingServices.OnDemandProcessing.RetrievalManager.PrefetchData(ReportInstance reportInstance, ParameterInfoCollection parameters, Boolean mergeTran)
   at Microsoft.ReportingServices.OnDemandProcessing.Merge.FetchData(ReportInstance reportInstance, Boolean mergeTransaction)
   at Microsoft.ReportingServices.ReportProcessing.Execution.ProcessReportOdpInitial.PreProcessSnapshot(OnDemandProcessingContext odpContext, Merge odpMerge, ReportInstance reportInstance, ReportSnapshot reportSnapshot)
   at Microsoft.ReportingServices.ReportProcessing.Execution.ProcessReportOdp.Execute(OnDemandProcessingContext& odpContext)
   at Microsoft.ReportingServices.ReportProcessing.Execution.RenderReportOdpInitial.ProcessReport(ProcessingErrorContext errorContext, ExecutionLogContext executionLogContext, UserProfileState& userProfileState)
   at Microsoft.ReportingServices.ReportProcessing.Execution.RenderReport.Execute(IRenderingExtension newRenderer)
   at Microsoft.ReportingServices.ReportProcessing.ReportProcessing.RenderReport(IRenderingExtension newRenderer, DateTime executionTimeStamp, ProcessingContext pc, RenderingContext rc, IChunkFactory yukonCompiledDefinition)
   at Microsoft.Reporting.LocalService.CreateSnapshotAndRender(ReportProcessing repProc, IRenderingExtension renderer, ProcessingContext pc, RenderingContext rc, SubreportCallbackHandler subreportHandler, ParameterInfoCollection parameters, DatasourceCredentialsCollection credentials)
   at Microsoft.Reporting.LocalService.Render(String format, String deviceInfo, String paginationMode, Boolean allowInternalRenderers, IEnumerable dataSources, CreateAndRegisterStream createStreamCallback)
   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings)

**Comment by lkosson** [comment]
Do you run your application in cloud infrastructure? If so, try explicitly setting `CurrentCulture` to a proper value, e.g. `en-GB` or `InvariantCulture` and see if error persists. If it does, please post a full stack trace, including inner exceptions.

**Comment by wahab2512** [comment]
The StackTrces are from my local machines and not from Cloud Deployments.

StackTrace:    
at System.Globalization.CultureInfo..ctor(Int32 culture, Boolean useUserOverride)
   at Microsoft.ReportingServices.ReportIntermediateFormat.DataSetCore.CreateCultureInfoFromLcid()
   at Microsoft.ReportingServices.OnDemandProcessing.OnDemandProcessingContext.SetComparisonInformation(DataSetCore dataSet)
   at Microsoft.ReportingServices.OnDemandProcessing.TablixProcessing.RuntimeOnDemandDataSet.InitializeDataSet()
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeAtomicDataSet.Process(ExecutedQuery existingQuery)
   at Microsoft.ReportingServices.OnDemandProcessing.RuntimeAtomicDataSet.ProcessConcurrent(Object threadSet)

**Comment by lkosson** [comment]
I see. Please check `CurrentCulture.LCID` of the thread you are using to render the report. It would appear as if it is some custom culture (`LCID=LOCALE_CUSTOM_UNSPECIFIED`) which cannot be re-created on demand.

Also, check if setting `CurrentCulture` of the thread to invariant culture changes anything.

Finally, try setting `Language` property of the report in your RDLC file to your appropriate culture. It should override the custom culture set for the thread.

**Comment by wahab2512** [comment]
I already checked Invariant Culture. This is the code I'm using and is producing the error.


`var cultureInfo = CultureInfo.InvariantCulture;`
`Thread.CurrentThread.CurrentCulture = cultureInfo;`
`mainStream = localReport.Render(renderType.ToString(), deviceInfo, PageCountMode.Actual, out string _, out string _, out string _, out string[] _, out Warning[] _);`

**Comment by lkosson** [comment]
And what about setting `Language` in RDLC?

**Comment by wahab2512** [comment]
That was the first thing I tried as I read about it in different blogs.

**Comment by lkosson** [comment]
Does the same error pops up when you run `ReportViewerCore.Sample.Console` project from this repo?

**Comment by wahab2512** [comment]
Same error when I run `ReportViewerCore.Sample.Console` project from repo on .NET 6.0.
Basically, I'm getting this error when migrating from .NET 5.0 to .NET 6.0.
My project is working fine on .NET 5.0.

**Comment by lkosson** [comment]
I'm not quite sure how to help you, as I am unable to reproduce the problem in my environment using VS2022 and .NET 6.0.0.

To debug the issue in your environment, you can set a breakpoint at `CreateCultureInfoFromLcid` method in `Microsoft.ReportingServices.ReportIntermediateFormat.DataSetCore` and inspect where does `0x1000` value in `LCID` comes from. Most likely it's a system-wide value provided by `Microsoft.ReportingServices.Diagnostics.Localization.DefaultReportServerSpecificCulture` which in turn uses `CultureInfo.InstalledUICulture`. That should get overriden in `Microsoft.ReportingServices.OnDemandProcessing.EvaluateReportLanguage` when `language` of the RDLC is explicitly set. At the moment my best guess is to check why it reverts back.

**Comment by wahab2512** [comment]
I can now confirm that the issue does not occur in my VPS which has Windows Server 2019 and has IIS 10 configured for production use. The problem occurs when I run the project in .NET 6.0 locally in my Visual Studio 2022. However, it doesn't occur when I publish my project to the VPS.

**Comment by wahab2512** [comment]
Now, I'm getting this error on VPS as well.

**Comment by lkosson** [comment]
Without a way to reproduce this error locally, all I can do is to ask you to try to debug by yourself using hints I have provided in a previous comment.

**Comment by wahab2512** [comment]
Okay, so I figured this out. The problem is probably because of a sort of breaking change in .NET 6 regarding Globalization and Cultures. As I am from Pakistan so I had my Region set as Pakistan, just changing the region to the UK fixed this issue. How exactly this works in the code of libraries used is still ambiguous to me though.

[Culture creation and case mapping in globalization-invariant mode](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/6.0/culture-creation-invariant-mode)

**Comment by lkosson** [comment]
While I can understand why VPS and/or cloud deployments might work in globalization-invariant mode (I had same issues with some of my apps), I don't understand why did it also happen on your desktop workstation.

Anyway - I'll wait and see if other users report similar issues. If so, I'll hard-code fallback `InvariantCulture` instead of relying on OS-reported one.

**Comment by lkosson** [comment]
I have added the workaround.

**Comment by breezycloud** [comment]
Concerning this Culture is not supported issue in .Net 6.0, unfortuantely i ran into same problem.
Thanks for this amazing library, keep up the good work. Hope it would be fixed soon.

**Comment by lkosson** [comment]
The workaround from that last commit should solve the issue. Feel free to compile the library and test it. I'll publish a new nuget package in a few days.
