### ISSUE TITLE
Could not find the resource "Microsoft.Reporting.NETCore.ReportPreviewStrings.resources" 

### ISSUE THREAD

**Issue by GeeSuth** [lkosson/reportviewercore#85]
Hey, 
I don't know what's reason for this issue 
``
Could not find the resource "Microsoft.Reporting.NETCore.ReportPreviewStrings.resources" among the resources "Microsoft.Reporting.CommonStrings.resources" embedded in the assembly "Microsoft.ReportViewer.NETCore", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
``
I Use Net 6

**Comment by lkosson** [comment]
Hi. Please provide a full stack trace of the exception and describe steps to reproduce the problem.

**Comment by GeeSuth** [comment]
Okay
I use .NET 6 
- First I install "ReportViewerCore.NETCore" 
- Create Controller for print 
And Use this Method 
``

            using (var db = new GeeSuthDbContext(options))
            {
                try
                {
                    var InvoObject = await db.INV_PUR_HD.FirstOrDefaultAsync(w => w.GUID_ID == Id);

                    var wwwroot = _IHostEnviroment.WebRootPath;
                    var reportpath = $"{wwwroot}\\Reports\\Invoice\\InvoReport.rdl";


                    using var report = new LocalReport();
                    report.ReportPath = reportpath;
                    report.DataSources.Add(new ReportDataSource("test", InvoObject));
                    var pdf = report.Render("PDF");


                    //var pdf = report.Render(renderFormat);
                    return File(pdf, System.Net.Mime.MediaTypeNames.Application.Pdf, "report.pdf");
                }
                catch (Exception ex)
                {

                    throw;
                }
``

**Comment by GeeSuth** [comment]
The Problem Exactly happen when I Add DataSource
If the report is without DataSource it's working

**Comment by GeeSuth** [comment]
``
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.Reporting.NETCore.ReportPreviewStrings.Keys.GetString(String key)
   at Microsoft.Reporting.NETCore.ReportPreviewStrings.get_BadReportDataSourceType()
   at Microsoft.Reporting.NETCore.ReportDataSource.set_Value(Object value)
   at Microsoft.Reporting.NETCore.ReportDataSource..ctor(String name, Object dataSourceValue)
   at GeeSuthClouds.API.Controllers.v1.Print.ReportController.<ExportToPdf>d__3.MoveNext() in E:\Windows Application\Mega\GeeSuthSoft Cloud\GeeSuthCloudSolution\GeeSuthClounds.API\Controllers\v1\Reports\ReportController.cs:line 47
``

**Comment by lkosson** [comment]
Your datasource is a single object (`InvoObject`), while it needs to be a `IEnumerable` such as array or a list.

**Comment by GeeSuth** [comment]
Yes, you are right, 
The error was not clear 
Thank you!

**Comment by lkosson** [comment]
The actual error got swallowed by another exception thrown when constructing error description - hence the ambiguous message. I'll fix that in upcoming release.

**Comment by GeeSuth** [comment]
Thank you!
but also get error 
``
   at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession() in C:\Users\GeeSuth-Acer\Documents\MEGA\reportviewercore\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\LocalReport.cs:line 812
   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings) in C:\Users\GeeSuth-Acer\Documents\MEGA\reportviewercore\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\LocalReport.cs:line 1022
   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings) in C:\Users\GeeSuth-Acer\Documents\MEGA\reportviewercore\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\LocalReport.cs:line 986
   at Microsoft.Reporting.NETCore.LocalReport.Render(String format, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings) in C:\Users\GeeSuth-Acer\Documents\MEGA\reportviewercore\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\LocalReport.cs:line 977
   at Microsoft.Reporting.NETCore.Report.Render(String format, String deviceInfo, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings) in C:\Users\GeeSuth-Acer\Documents\MEGA\reportviewercore\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\Report.cs:line 152
   at Microsoft.Reporting.NETCore.Report.Render(String format, String deviceInfo) in C:\Users\GeeSuth-Acer\Documents\MEGA\reportviewercore\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\Report.cs:line 147
   at Microsoft.Reporting.NETCore.Report.Render(String format) in C:\Users\GeeSuth-Acer\Documents\MEGA\reportviewercore\Microsoft.ReportViewer.NETCore\Microsoft.Reporting.NETCore\Report.cs:line 137
   at GeeSuthClouds.API.Controllers.v1.Print.ReportController.<ExportToPdf>d__3.MoveNext() in E:\Windows Application\Mega\GeeSuthSoft Cloud\GeeSuthCloudSolution\GeeSuthClounds.API\Controllers\v1\Reports\ReportController.cs:line 47
``

**Comment by GeeSuth** [comment]
it's working after install this package: 
- Microsoft.CodeAnalysis
- System.CodeDom
